import Image from 'next/image'

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h1>Home</h1>
    </div>
  )
}
